### ISSUE TITLE
[Bug] Manhwa18 notifications are not working correctly

### ISSUE THREAD

**Issue by G33Zuss** [Paperback-iOS/h-extensions#8]
I get constant updates from titles I follow locally even when I've read the chapter. And even when I haven't the updates just pile on, this happens multiple times a day. I'm going to assume this has something to do with how the chapters are pulled from the site, considering the issue you've made yourself.
![D3EF2CC9-10E7-4274-B7FB-3B70294D7B2F](https://user-images.githubusercontent.com/24464471/89949441-d1ca1480-dc1f-11ea-89b6-1655d5833d1a.png)

**Comment by TheNetsky** [comment]
I will close this issue for now since this bug was from the non-promises version, which is no longer supported. If you still encounter these bugs or any bug with Manhwa18, please comment these on #55
